language: python
python:
- '3.4'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  - python3 manage.py migrate --noinput
script: .travis/script.sh
deploy:
  provider: heroku
  api_key:
    secure: vlACdu6HghF44Ifka2ezPB0cVkdOcHAgdqwJYDQ75iBEo7SAm6CN+dbnW76IY51wSIx7bu9vl0G3uvSvCpo7PrzCiasf76xyRkJQATTIQAbsCvphRyCfNQLlnwMjPR1TJXdZdd0ana8r62ti+R/7I0TCzDFZPi5T+/1cFWf3PLo=
  strategy: git
  app: writing-sandbox
  on: master
addons:
  sauce_connect:
    username: leclipse
    access_key:
      secure: Lu1xC2xxjw1oFzI9jsZbQ/2bmf78YPsr2O6motZKsbnNz/d9G5v4LoE+5cViMpNKx3VaIAeo0HpbJICWpjINJ9U+sHu26ncxnP2Ja99Q82QdR1bFbMc73zHULKFWutGqdE2RkSO+nFHRnZ3x7HEpmNmcm9yOyEXJ9Ndt5aTI9IY=
after_deploy: .travis/after_deploy.sh
